In [1]:
from shoppingassistant.process_data import load_dataframes
import pandas as pd
import numpy as np

In [ ]:
df, df_trans = load_dataframes()

article_id = df.iloc[0]["article_id"]
print(f"Article ID: {article_id}")
# Get customer_ids who bought the given article_id
customers = df_trans[df_trans["article_id"] == article_id]["customer_id"].unique() # Those customers bought the article_id

✅ Filtered data already exists.
Article ID: 181160009

In [17]:
df_trans[df_trans['customer_id']==customers[5]]

,t_dat,article_id,price,customer_id
7525,2018-09-27,578198002,0.044051,282cf48f1cf982fbe1512c48720807002abb04447ad097...
7526,2018-09-27,181160009,0.028797,282cf48f1cf982fbe1512c48720807002abb04447ad097...

In [42]:
most_sold_with_article = pd.DataFrame(columns=['article_id', 'price'])
most_sold_with_article

Empty DataFrame
Columns: [article_id, price]
Index: []

In [23]:
cust = customers[5]
df_cust = df_trans[df_trans['customer_id']==cust] # Transactions of that customer
sell_date = df_cust[df_cust['article_id']==article_id]['t_dat'].values[0] # Date when the article was bought
sell_date

np.datetime64('2018-09-27T00:00:00.000000000')

In [24]:
df_cust

,t_dat,article_id,price,customer_id
7525,2018-09-27,578198002,0.044051,282cf48f1cf982fbe1512c48720807002abb04447ad097...
7526,2018-09-27,181160009,0.028797,282cf48f1cf982fbe1512c48720807002abb04447ad097...

In [35]:
articles_bought_same_day = df_cust[df_cust['t_dat']==sell_date]
articles_bought_same_day = articles_bought_same_day[articles_bought_same_day!=article_id]
articles_bought_same_day = articles_bought_same_day.dropna()

In [36]:
articles_bought_same_day

,t_dat,article_id,price,customer_id
7525,2018-09-27,578198002.0,0.044051,282cf48f1cf982fbe1512c48720807002abb04447ad097...

In [38]:
articles_bought_same_day = articles_bought_same_day.sort_values('price')
articles_bought_same_day

,t_dat,article_id,price,customer_id
7525,2018-09-27,578198002.0,0.044051,282cf48f1cf982fbe1512c48720807002abb04447ad097...

In [43]:
most_sold_with_article = pd.concat([most_sold_with_article, articles_bought_same_day[['article_id', 'price']].head(1)], ignore_index=True)
most_sold_with_article

/tmp/ipykernel_133479/1710330362.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  most_sold_with_article = pd.concat([most_sold_with_article, articles_bought_same_day[['article_id', 'price']].head(1)], ignore_index=True)

    article_id     price
0  578198002.0  0.044051

In [ ]:
df_cust_same_day = df_cust[df_cust['t_dat']==sell_date]

articles_bought_same_day = df_cust_same_day['article_id'].values
articles_bought_same_day = articles_bought_same_day[articles_bought_same_day != article_id] # Remove the original article_id
articles_bought_same_day = articles_bought_same_day.sort_values('price')
articles_bought_same_day

In [54]:
for cust in customers:
    df_cust = df_trans[df_trans['customer_id']==cust] # Transactions of that customer
    sell_date = df_cust[df_cust['article_id']==article_id]['t_dat'].values[0] # Date when the article was bought
    articles_bought_same_day = df_cust[df_cust['t_dat']==sell_date]
    articles_bought_same_day = articles_bought_same_day[articles_bought_same_day!=article_id]
    articles_bought_same_day = articles_bought_same_day.dropna()
    articles_bought_same_day = articles_bought_same_day.sort_values('price')
    most_sold_with_article = pd.concat([most_sold_with_article, articles_bought_same_day[['article_id', 'price']].head(1)], ignore_index=True)
most_sold_with_article = most_sold_with_article.sort_values('price', ascending=False)

revenue_with_article = most_sold_with_article.groupby('article_id').sum().reset_index()
revenue_with_article = revenue_with_article.sort_values('price', ascending=False)
revenue_with_article

     article_id     price
7   619234001.0  0.548949
4   578198002.0  0.308356
2   535176001.0  0.292780
6   589228001.0  0.284644
1   517762001.0  0.162610
0   401729003.0  0.152441
9   632651002.0  0.121932
8   622964004.0  0.060915
10  650506002.0  0.060915
3   546269007.0  0.050746
5   580684001.0  0.032441

In [52]:
print(f"The most sold items with article {article_id} are:")
most_sold_with_article

The most sold items with article 181160009 are:

     article_id     price
39  619234001.0  0.050831
34  619234001.0  0.050831
35  619234001.0  0.050831
36  619234001.0  0.050831
32  535176001.0  0.048797
33  535176001.0  0.048797
44  535176001.0  0.048797
31  535176001.0  0.048797
29  589228001.0  0.047441
28  589228001.0  0.047441
30  589228001.0  0.047441
43  589228001.0  0.047441
26  578198002.0  0.044051
25  578198002.0  0.044051
27  578198002.0  0.044051
24  578198002.0  0.044051
37  578198002.0  0.044051
21  619234001.0  0.040661
48  619234001.0  0.040661
22  619234001.0  0.040661
23  619234001.0  0.040661
41  517762001.0  0.027102
19  517762001.0  0.027102
18  517762001.0  0.027102
20  517762001.0  0.027102
16  401729003.0  0.025407
17  401729003.0  0.025407
47  401729003.0  0.025407
15  401729003.0  0.025407
12  632651002.0  0.020322
14  632651002.0  0.020322
13  632651002.0  0.020322
38  632651002.0  0.020322
8   622964004.0  0.010153
6   650506002.0  0.010153
7   622964004.0  0.010153
9   622964004.0  0.010153
40  622964004.0  0.010153
46  650506002.0  0.010153
11  650506002.0  0.010153
10  650506002.0  0.010153
4   546269007.0  0.008458
5   546269007.0  0.008458
42  546269007.0  0.008458
3   546269007.0  0.008458
1   580684001.0  0.005407
2   580684001.0  0.005407
0   580684001.0  0.005407
45  580684001.0  0.005407